import {
  UI_CARD_PADDING_COMPACT,
  UI_CARD_SHELL_CLASS,
  UI_CARD_SHELL_SOFT_BORDER_CLASS,
  UI_HELPER_TEXT_CLASS,
  UI_INSET_PANEL_CLASS,
  UI_LINK_CARD_INTERACTION_CLASS,
  UI_SECTION_STACK_CLASS,
  UI_SECTION_TITLE_CLASS,
} from "@/lib/ui/productUiTokens";

/** Shared presentation tokens for admin operational surfaces (RC-2E / 2F). */
export const ADMIN_LIST_CARD_CLASS = `block ${UI_CARD_SHELL_SOFT_BORDER_CLASS} ${UI_CARD_PADDING_COMPACT} ${UI_LINK_CARD_INTERACTION_CLASS}`;

export const ADMIN_QUEUE_CARD_CLASS = `${UI_CARD_SHELL_SOFT_BORDER_CLASS} ${UI_CARD_PADDING_COMPACT}`;

export const ADMIN_DETAIL_CARD_CLASS = UI_CARD_SHELL_CLASS;

export const ADMIN_DETAIL_INSET_CLASS = UI_INSET_PANEL_CLASS;

export const ADMIN_SECTION_TITLE_CLASS = UI_SECTION_TITLE_CLASS;

export const ADMIN_SECTION_MUTED_CLASS = `mt-0.5 ${UI_HELPER_TEXT_CLASS} leading-relaxed`;

export const ADMIN_DETAIL_STACK_CLASS = `mt-3 ${UI_SECTION_STACK_CLASS} sm:mt-4`;

export {
  UI_DETAILS_BODY_CLASS as ADMIN_DETAILS_BODY_CLASS,
  UI_DETAILS_DISCLOSURE_CLASS as ADMIN_DETAILS_DISCLOSURE_CLASS,
  UI_DETAILS_SUMMARY_COMPACT_CLASS as ADMIN_DETAILS_SUMMARY_CLASS,
} from "@/lib/ui/productUiTokens";
