/**
 * Raw "House Cleaning {area}" labels from search/operations data.
 * Normalized by `locationRegistry` — do not use directly in UI.
 */
export const HOUSE_CLEANING_AREA_LABELS = [
  "House Cleaning Sea Point",
  "House Cleaning Green Point",
  "House Cleaning Camps Bay",
  "House Cleaning Bantry Bay",
  "House Cleaning Fresnaye",
  "House Cleaning Mouille Point",
  "House Cleaning Three Anchor Bay",
  "House Cleaning Clifton",
  "House Cleaning Bakoven",
  "House Cleaning Llandudno",
  "House Cleaning Hout Bay",
  "House Cleaning Claremont",
  "House Cleaning Rondebosch",
  "House Cleaning Wynberg",
  "House Cleaning Observatory",
  "House Cleaning Newlands",
  "House Cleaning Kenilworth",
  "House Cleaning Plumstead",
  "House Cleaning Diep River",
  "House Cleaning Ottery",
  "House Cleaning Lansdowne",
  "House Cleaning Crawford",
  "House Cleaning Athlone",
  "House Cleaning Constantia",
  "House Cleaning Tokai",
  "House Cleaning Bergvliet",
  "House Cleaning Meadowridge",
  "House Cleaning Southfield",
  "House Cleaning Retreat",
  "House Cleaning Steenberg",
  "House Cleaning Heathfield",
  "House Cleaning Mowbray",
  "House Cleaning Rosebank",
  "House Cleaning Woodstock",
  "House Cleaning Salt River",
  "House Cleaning Gardens",
  "House Cleaning Oranjezicht",
  "House Cleaning Vredehoek",
  "House Cleaning Tamboerskloof",
  "House Cleaning De Waterkant",
  "House Cleaning Foreshore",
  "House Cleaning Century City",
  "House Cleaning Milnerton",
  "House Cleaning Tableview",
  "House Cleaning Table View",
  "House Cleaning Parklands",
  "House Cleaning Blouberg",
  "House Cleaning Bloubergstrand",
  "House Cleaning West Beach",
  "House Cleaning Big Bay",
  "House Cleaning Sunset Beach",
  "House Cleaning Bellville",
  "House Cleaning Durbanville",
  "House Cleaning D'urbanvale",
  "House Cleaning Brackenfell",
  "House Cleaning Kraaifontein",
  "House Cleaning Kuils River",
  "House Cleaning Parow",
  "House Cleaning Goodwood",
  "House Cleaning Elsies River",
  "House Cleaning Delft",
  "House Cleaning Blue Downs",
  "House Cleaning Eerste River",
  "House Cleaning Somerset West",
  "House Cleaning Strand",
  "House Cleaning Gordon's Bay",
  "House Cleaning Fish Hoek",
  "House Cleaning Muizenberg",
  "House Cleaning Kommetjie",
  "House Cleaning Noordhoek",
  "House Cleaning Simon's Town",
  "House Cleaning Pinelands",
  "House Cleaning Edgemead",
  "House Cleaning Bothasig",
  "House Cleaning Montague Gardens",
  "House Cleaning Brooklyn",
  "House Cleaning Brooklyn Chestnut",
  "House Cleaning Amandelrug",
  "House Cleaning Belhar",
  "House Cleaning Bishopscourt",
  "House Cleaning Capri Village",
  "House Cleaning Crossroads",
  "House Cleaning Grassy Park",
  "House Cleaning Macassar",
  "House Cleaning Marina da Gama",
  "House Cleaning Mitchells Plain",
  "House Cleaning Nyanga",
  "House Cleaning Ottery East",
  "House Cleaning Pelican Park",
  "House Cleaning Protea Valley",
  "House Cleaning Scarborough",
  "House Cleaning St James",
  "House Cleaning Walmer Estate",
  "House Cleaning Youngsfield",
  "House Cleaning Zeekoevlei",
  "House Cleaning Atlantis",
  "House Cleaning Melkbosstrand",
  "House Cleaning Joe Slovo Park",
  "House Cleaning Khayelitsha",
  "House Cleaning Langa",
  "House Cleaning Maitland",
  "House Cleaning Ndabeni",
  "House Cleaning Ottery West",
  "House Cleaning Philippi",
  "House Cleaning Rylands",
  "House Cleaning Wetton",
  "House Cleaning Wynberg North",
  "House Cleaning Cape Gate",
  "House Cleaning Sunningdale",
  "House Cleaning Stellenbosch",
  "House Cleaning Paarl",
  "House Cleaning Wellington",
  "House Cleaning Worcester",
  "House Cleaning Hermanus",
  "House Cleaning George",
  "House Cleaning Knysna",
  "House Cleaning Mossel Bay",
  "House Cleaning Plettenberg Bay",
  "House Cleaning Oudshoorn",
  "House Cleaning Oudtshoorn",
  "House Cleaning Langebaan",
  "House Cleaning Saldanha",
  "House Cleaning Vredenburg",
  "House Cleaning Malmesbury",
  "House Cleaning Swellendam",
  "House Cleaning Robertson",
  "House Cleaning Montagu",
  "House Cleaning Caledon",
  "House Cleaning Grabouw",
  "House Cleaning Bredasdorp",
  "House Cleaning Beaufort West",
  "House Cleaning Ceres",
  "House Cleaning Sedgefield",
  "House Cleaning Wilderness",
  "House Cleaning Still Bay",
  "House Cleaning Albertinia",
  "House Cleaning Barrydale",
  "House Cleaning Prince Albert",
  "House Cleaning Tulbagh",
  "House Cleaning Franschhoek",
  "House Cleaning Gansbaai",
  "House Cleaning Kleinmond",
  "House Cleaning Betty's Bay",
  "House Cleaning Rooi Els",
  "House Cleaning Pringle Bay",
  "House Cleaning Helderberg",
  "House Cleaning Northern Suburbs",
  "House Cleaning Southern Suburbs",
  "House Cleaning Cape Flats",
  "House Cleaning Cape Town CBD",
] as const;
