import { describe, expect, it } from "vitest";
import { collectServiceRoleImporterPaths } from "./staticGuardSupport";

/**
 * Modules allowed to import `@/lib/supabase/serviceRole` for server-side lifecycle work.
 * Add a path here only after review. see docs/security/command-boundary-static-guards.md
 */
export const ALLOWED_SERVICE_ROLE_LIFECYCLE_IMPORTERS = new Set([
  "lib/supabase/serviceRole.ts",
  "features/bookings/server/commands/runBookingCommand.ts",
  "features/payments/server/finalizePaidBooking.ts",
  "features/payments/server/processPaystackChargeFailure.ts",
  "features/payments/server/upsertBookingFromPaystack.ts",
  "features/payments/server/initializePayment.ts",
  "features/payments/server/completePaystackBookingCheckout.ts",
  "features/payments/server/verifyPayment.ts",
  "features/zoho-invoice-payments/server/zohoInvoicePaymentRepository.ts",
  "features/zoho-invoice-payments/server/retryZohoInvoiceReconciliation.ts",
  "features/zoho-invoice-payments/server/processZohoInvoiceChargeSuccess.ts",
  "features/zoho-invoice-payments/server/processZohoInvoiceChargeFailure.ts",
  "features/zoho-invoice-payments/server/loadZohoInvoicePaymentDiagnostics.ts",
  "features/zoho-invoice-payments/server/zohoInvoicePaymentMethodRepository.ts",
  "features/zoho-invoice-payments/server/zohoInvoiceAuthorizationChargeRepository.ts",
  "features/zoho-invoice-payments/server/processZohoInvoiceAuthorizationChargeSuccess.ts",
  "features/zoho-invoice-payments/server/processZohoInvoiceAuthorizationChargeFailure.ts",
  "features/zoho-invoice-payments/server/retryZohoInvoiceAuthorizationChargeReconciliation.ts",
  "features/zoho-invoice-payments/server/loadZohoPaymentGovernance.ts",
  "features/zoho-invoice-payments/server/zohoInvoicePaymentCronRunRepository.ts",
  "features/admin/server/entityArchive/archiveBookingAdminCommand.ts",
  "features/admin/server/entityArchive/archiveCleanerAdminCommand.ts",
  "features/admin/server/entityArchive/archiveCustomerAdminCommand.ts",
  "features/admin/server/entityArchive/hardDeleteBookingAdminCommand.ts",
  "features/cleaner-applications/server/adminCleanerApplicationsReadModel.ts",
  "features/cleaner-applications/server/convertApplicationToCleaner.ts",
  "features/cleaner-applications/server/submitCleanerApplication.ts",
  "features/cleaners/server/admin/createCleaner.ts",
  "features/cleaners/server/admin/updateCleanerProfile.ts",
  "features/cleaners/server/lifecycle/completeCleanerOnboarding.ts",
  "features/customers/server/admin/adminCustomersReadModel.ts",
  "features/customers/server/admin/createCustomer.ts",
  "features/customers/server/admin/updateCustomer.ts",
  "features/notifications/server/resolveCustomerEmailOrNull.ts",
  "features/support/server/executeApprovedBookingRescheduleRequest.ts",
  "app/api/cron/generate-recurring-occurrences/route.ts",
  "features/bookings/server/lock/createBookingPaymentLock.ts",
  "features/bookings/server/admin/adminCreateBookingDraftFacade.ts",
  "features/bookings/server/admin/adminCreatePendingPaymentBookingFacade.ts",
  "features/bookings/server/admin/adminGeneratePaymentLinkFacade.ts",
  "features/bookings/server/admin/adminSendPaymentRequestNotificationFacade.ts",
  "features/bookings/server/admin/adminRecordOfflinePaymentFacade.ts",
  "features/bookings/server/admin/authorizeMonthlyAccountServiceFacade.ts",
  "features/bookings/server/admin/adminRecordPaymentLinkCopiedFacade.ts",
  "features/customer-payments/server/customerPaymentHistory.ts",
  "features/production-rollout/server/productionRolloutChecklistRepository.ts",
  "features/bookings/server/lock/createPaymentRetryLock.ts",
  "features/bookings/server/lock/assertActiveLock.ts",
  "features/bookings/server/lock/validateCleanerPreference.ts",
  "features/cleaners/server/getAvailableCleaners.ts",
  "features/cleaners/server/lifecycle/deactivateCleaner.ts",
  "features/cleaners/server/lifecycle/suspendCleaner.ts",
  "features/cleaners/server/lifecycle/reactivateCleaner.ts",
  "features/cleaners/server/lifecycle/unsuspendCleaner.ts",
  "features/cleaners/server/lifecycle/archiveCleaner.ts",
  "features/cleaners/server/lifecycle/cancelCleanerOpenOffersCommand.ts",
  "features/assignments/server/adminManualDispatchOffer.ts",
  "features/assignments/server/adminAssignmentRecovery.ts",
  "features/assignments/server/adminReplaceOpenOffer.ts",
  "features/assignments/server/adminDeferredDispatchNow.ts",
  "features/assignments/server/adminSupportDispatchOffer.ts",
  "features/dashboards/server/recordAdminTeamRequestFulfillment.ts",
  "features/dashboards/server/recordAdminTeamSupportOps.ts",
  "app/api/cron/rollup-assignment-metrics/route.ts",
  "app/api/cron/expire-assignment-offers/route.ts",
  "app/api/cron/expire-pending-payments/route.ts",
  "app/api/cron/recover-assignment-after-payment/route.ts",
  "app/api/cron/dispatch-deferred-assignments/route.ts",
  "app/api/cron/reconcile-zoho-invoice-payments/route.ts",
  "app/api/cron/sync-shalean-sales-to-zoho/route.ts",
  "app/api/cron/sync-zoho-refunds-credits/route.ts",
  "features/zoho-sales-sync/server/zohoSalesSyncRepository.ts",
  "features/zoho-sales-sync/server/loadZohoSalesSyncDiagnostics.ts",
  "features/zoho-sales-sync/server/retryZohoSalesSync.ts",
  "features/zoho-sales-sync/server/registerExistingZohoSalesSync.ts",
  "features/zoho-sales-sync/server/loadShaleanSaleSource.ts",
  "features/zoho-sales-sync/server/syncShaleanSaleToZoho.ts",
  "features/zoho-sales-sync/server/zohoRefundCreditSyncRepository.ts",
  "features/zoho-sales-sync/server/loadZohoRefundCreditDiagnostics.ts",
  "features/zoho-sales-sync/server/retryZohoRefundCreditSync.ts",
  "features/zoho-sales-sync/server/loadRefundCreditSource.ts",
  "features/zoho-sales-sync/server/syncZohoRefundCreditToZoho.ts",
  "features/zoho-sales-sync/server/registerZohoRefundCredit.ts",
  "features/finance-reconciliation/server/financeReconciliationReadModel.ts",
  "features/accounting-close/server/accountingCloseReadModel.ts",
  "features/tax-reports/server/taxReportReadModel.ts",
  "features/corporate-statements/server/corporateStatementReadModel.ts",
  "features/finance-analytics/server/financeAnalyticsReadModel.ts",
  "features/production-rollout/server/productionRolloutReadModel.ts",
  "features/monthly-billing/server/customerBillingAccountRepository.ts",
  "features/monthly-billing/server/monthlyInvoiceBatchRepository.ts",
  "features/monthly-billing/server/customerBillingAccountReadModel.ts",
  "features/monthly-billing/server/monthlyInvoiceBatchReadModel.ts",
  "features/monthly-billing/server/enableCustomerMonthlyBillingAccountFacade.ts",
  "features/monthly-billing/server/disableCustomerMonthlyBillingAccountFacade.ts",
  "features/monthly-billing/server/updateCustomerBillingTermsFacade.ts",
  "features/monthly-billing/server/linkCustomerZohoCustomerFacade.ts",
  "features/monthly-billing/server/accrueMonthlyInvoiceItemForBooking.ts",
  "features/monthly-billing/server/loadMonthlyInvoiceAccrualDiagnostics.ts",
  "features/monthly-billing/server/generateZohoMonthlyInvoiceFacade.ts",
  "features/monthly-billing/server/loadMonthlyInvoiceGenerationDiagnostics.ts",
  "features/monthly-billing/server/syncZohoMonthlyInvoicePaymentStatus.ts",
  "features/monthly-billing/server/loadMonthlyInvoicePaymentSyncDiagnostics.ts",
  "app/api/cron/sync-monthly-invoice-payments/route.ts",
  "app/api/cron/mark-monthly-invoices-overdue/route.ts",
  "app/api/cron/process-monthly-invoice-reminders/route.ts",
  "app/api/admin/bookings/[bookingId]/assist-feedback/route.ts",
  "app/api/admin/bookings/[bookingId]/assist-qa-checklist/route.ts",
  "app/api/admin/bookings/assist-incidents/review/route.ts",
  "features/bookings/server/admin/adminAssistedBookingDiagnosticsReadModel.ts",
  "features/bookings/server/admin/adminAssistedIncidentReviewRepository.ts",
  "features/bookings/server/admin/loadAdminAssistQaChecklist.ts",
  "features/bookings/server/admin/loadAdminAssistedOperatorFeedback.ts",
  "features/bookings/server/admin/loadAdminAssistedPilotQaPanel.ts",
  "features/bookings/server/admin/loadAdminAssistedProductionLearning.ts",
  "features/bookings/server/admin/loadAdminAssistedProductionStatus.ts",
  "features/bookings/server/admin/loadAdminBookingAssistSummary.ts",
  "features/bookings/server/admin/loadAdminBookingRecurringVerification.ts",
  "features/bookings/server/admin/validateAdminWizardBillingMode.ts",
  "features/monthly-billing/server/autoSendMonthlyInvoiceAfterGeneration.ts",
  "features/monthly-billing/server/customerBillingAccountGovernanceRepository.ts",
  "features/monthly-billing/server/customerMonthlyInvoicesReadModel.ts",
  "features/monthly-billing/server/loadMonthlyAccountAuthorizationContext.ts",
  "features/monthly-billing/server/loadMonthlyAccountExposure.ts",
  "features/monthly-billing/server/loadMonthlyCollectionsDashboard.ts",
  "features/monthly-billing/server/loadMonthlyGovernanceDashboard.ts",
  "features/monthly-billing/server/loadMonthlyGovernanceTimelineForCustomer.ts",
  "features/monthly-billing/server/loadMonthlyInvoiceOperationsDiagnostics.ts",
  "features/monthly-billing/server/markMonthlyInvoiceCollectionsState.ts",
  "features/monthly-billing/server/markMonthlyInvoiceOverdue.ts",
  "features/monthly-billing/server/monthlyAccountCollectionsNotesRepository.ts",
  "features/monthly-billing/server/monthlyAccountGovernanceFacade.ts",
  "features/monthly-billing/server/processMonthlyInvoiceRemindersForCron.ts",
  "features/monthly-billing/server/resendMonthlyInvoiceToCustomer.ts",
  "features/monthly-billing/server/sendMonthlyInvoiceReminder.ts",
  "features/monthly-billing/server/sendMonthlyInvoiceToCustomer.ts",
  "features/monthly-billing/server/submitCustomerMonthlyInvoiceDisputeRequest.ts",
  "features/monthly-billing/server/updateMonthlyAccountFinanceReview.ts",
  "features/bookings/server/commands/runBookingCommand.ts",
  // Notification cron passes service-role client into the worker; worker does not import serviceRole.
  "app/api/cron/process-notification-outbox/route.ts",
  "app/api/cron/cleanup-notification-retention/route.ts",
  "app/api/cron/rollup-notification-metrics/route.ts",
  "features/notifications/server/adminRequeueNotificationOutbox.ts",
  "features/notifications/server/resolveCleanerEmail.ts",
  "scripts/recoverAssignmentAfterPayment.ts",
  "scripts/repairOrphanedAssignments.ts",
]);

describe("service role lifecycle write registry (static)", () => {
  it("only approved modules import the service role client", () => {
    const importers = collectServiceRoleImporterPaths();
    const unexpected = importers.filter((p) => !ALLOWED_SERVICE_ROLE_LIFECYCLE_IMPORTERS.has(p));

    expect(
      unexpected,
      `New service-role import(s) detected. Add to ALLOWED_SERVICE_ROLE_LIFECYCLE_IMPORTERS after review:\n${unexpected.join("\n")}`,
    ).toEqual([]);
  });

  it("registry entries still exist on disk", () => {
    const importers = new Set(collectServiceRoleImporterPaths());
    const missingFromCodebase = [...ALLOWED_SERVICE_ROLE_LIFECYCLE_IMPORTERS].filter(
      (p) => p !== "lib/supabase/serviceRole.ts" && !importers.has(p),
    );

    expect(
      missingFromCodebase,
      "Stale registry entries (file no longer imports service role):",
    ).toEqual([]);
  });
});
