import type { CronJobDefinition } from "./cronHealthTypes";

/** Launch-critical and supporting background jobs for Regular Cleaning. */
export const REGULAR_CLEANING_CRON_JOBS: CronJobDefinition[] = [
  {
    id: "expire-pending-payments",
    name: "Expire pending payments",
    routePath: "/api/cron/expire-pending-payments",
    scheduleSource: "supabase_pg_cron",
    scheduleHint: "Hourly at :00 UTC (pg_cron job expire-pending-payments-hourly)",
    expectedFrequencyMinutes: 60,
    docPath: "docs/operations/expire-pending-payments-cron.md",
    launchRequired: true,
  },
  {
    id: "expire-assignment-offers",
    name: "Expire assignment offers",
    routePath: "/api/cron/expire-assignment-offers",
    scheduleSource: "supabase_pg_cron",
    scheduleHint: "Hourly at :00 UTC (pg_cron job expire-assignment-offers-hourly)",
    expectedFrequencyMinutes: 60,
    docPath: "docs/operations/expire-assignment-offers-cron.md",
    launchRequired: true,
  },
  {
    id: "recover-assignment-after-payment",
    name: "Recover assignment after payment",
    routePath: "/api/cron/recover-assignment-after-payment",
    scheduleSource: "supabase_pg_cron",
    scheduleHint: "Every 15m UTC (pg_cron job recover-assignment-after-payment-quarter-hourly)",
    expectedFrequencyMinutes: 60,
    docPath: "docs/operations/assignment-recovery.md",
    launchRequired: true,
  },
  {
    id: "dispatch-deferred-assignments",
    name: "Dispatch deferred assignments",
    routePath: "/api/cron/dispatch-deferred-assignments",
    scheduleSource: "feature_gated",
    scheduleHint: "Hourly when DEFERRED_ASSIGNMENT_ENABLED (pg_cron dispatch-deferred-assignments-hourly)",
    expectedFrequencyMinutes: 60,
    docPath: "docs/operations/dispatch-deferred-assignments-cron.md",
    launchRequired: false,
    featureFlagEnv: "DEFERRED_ASSIGNMENT_ENABLED",
  },
  {
    id: "generate-recurring-occurrences",
    name: "Generate recurring occurrences",
    routePath: "/api/cron/generate-recurring-occurrences",
    scheduleSource: "ops_configured",
    scheduleHint: "Hourly or every 6h UTC (see generate-recurring-occurrences-cron.md)",
    expectedFrequencyMinutes: 360,
    docPath: "docs/operations/generate-recurring-occurrences-cron.md",
    launchRequired: true,
  },
];
