import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { AdminCorporateStatementsDashboard } from "./AdminCorporateStatementsDashboard";

describe("AdminCorporateStatementsDashboard", () => {
  const baseSummary = {
    customerLabel: "Acme Corp",
    customerEmail: "accounts@acme.com",
    periodStart: "2026-07-01T00:00:00.000Z",
    periodEnd: "2026-07-31T23:59:59.999Z",
    openingBalanceCents: 0,
    invoiceChargesCents: 10000,
    paymentsCents: 10000,
    refundsCreditsCents: 0,
    closingBalanceCents: 0,
    outstandingCount: 0,
    paidCount: 1,
  };

  it("renders summary, table, export, print layout, and no mutation buttons", () => {
    const html = renderToStaticMarkup(
      <AdminCorporateStatementsDashboard
        data={{
          summary: baseSummary,
          items: [
            {
              id: "zoho_invoice:1",
              date: "2026-07-05T10:00:00.000Z",
              type: "payment",
              reference: "pay-ref",
              invoiceNumber: "INV-001",
              description: "Payment received for INV-001",
              debitCents: 0,
              creditCents: 10000,
              balanceCents: 0,
              status: "paid",
            },
          ],
          openingBalanceNote: "Opening balance reflects Shalean-recorded activity.",
        }}
        filters={{
          customerEmail: "accounts@acme.com",
          periodType: "monthly",
          from: baseSummary.periodStart,
          to: baseSummary.periodEnd,
        }}
        hasCustomerIdentifier={true}
      />,
    );

    expect(html).toContain("Corporate client statement");
    expect(html).toContain("Opening balance");
    expect(html).toContain("Export CSV");
    expect(html).toContain("Print statement");
    expect(html).toContain("Shalean Cleaning Services");
    expect(html).toContain("Statement generated by Shalean Cleaning Services.");
    expect(html).toContain("pay-ref");
    expect(html).not.toContain("Mark paid");
    expect(html).not.toContain("authorization_code");
  });

  it("renders empty state when no customer identifier", () => {
    const html = renderToStaticMarkup(
      <AdminCorporateStatementsDashboard
        data={null}
        filters={{ periodType: "monthly" }}
        hasCustomerIdentifier={false}
      />,
    );

    expect(html).toContain("Enter a customer email");
  });

  it("renders no activity empty state", () => {
    const html = renderToStaticMarkup(
      <AdminCorporateStatementsDashboard
        data={{
          summary: baseSummary,
          items: [],
          openingBalanceNote: "Note",
        }}
        filters={{
          customerEmail: "accounts@acme.com",
          periodType: "monthly",
          from: baseSummary.periodStart,
          to: baseSummary.periodEnd,
        }}
        hasCustomerIdentifier={true}
      />,
    );

    expect(html).toContain("No statement activity for this period.");
  });
});
